In [1]:
import numpy as np

In [2]:
# Task_1

In [3]:
a = np.array([[1,6],
          [2,8],
          [3,11],
          [3,10],
          [1,7]])

In [6]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [7]:
# Task_2

In [20]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [21]:
# Task_3

In [22]:
a_centered_sp = a_centered[:,0]@a_centered[:,0]
a_centered_sp

4.0

In [23]:
a_centered_sp/(5-1)

1.0

In [ ]:
#Task4:

In [25]:
m = np.cov(a.T)
m

array([[1. , 2. ],
       [2. , 4.3]])

In [26]:
cov = m[0,0]
cov

1.0